export const FAKE_MOVIE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/yF1eOkaYvwiORauRCPWznV9xVvi.jpg",
    genre_ids: [28, 12, 878],
    id: 298618,
    original_language: "en",
    original_title: "The Flash",
    overview:
      "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
    popularity: 5125.277,
    poster_path: "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    release_date: "2023-06-13",
    title: "The Flash",
    video: false,
    vote_average: 6.9,
    vote_count: 1829,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: null,
    id: 3556,
    title: "Mad Dog Coll",
    original_language: "en",
    original_title: "Mad Dog Coll",
    overview:
      'Killer Vincent "Mad Dog" Coll moves in on gangster Dutch Schultz in 1920s New York.',
    poster_path: "/gQjMkGtoekvsgQNWGiisDF3VY5y.jpg",
    media_type: "movie",
    genre_ids: [80, 18],
    popularity: 2.314,
    release_date: "1961-05-12",
    video: false,
    vote_average: 6.167,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
    id: 667538,
    title: "Transformers: Rise of the Beasts",
    original_language: "en",
    original_title: "Transformers: Rise of the Beasts",
    overview:
      "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
    poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 878],
    popularity: 2516.301,
    release_date: "2023-06-06",
    video: false,
    vote_average: 7.53,
    vote_count: 2312,
  },
  {
    adult: false,
    backdrop_path: "/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
    id: 346698,
    title: "Barbie",
    original_language: "en",
    original_title: "Barbie",
    overview:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    media_type: "movie",
    genre_ids: [35, 12, 14],
    popularity: 3075.774,
    release_date: "2023-07-19",
    video: false,
    vote_average: 7.518,
    vote_count: 2287,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 114472,
    title: "Daybreak in Udi",
    original_language: "en",
    original_title: "Daybreak in Udi",
    overview:
      "An African tribe in the Eastern Nigerian village of Umana work to build a maternity hospital, with the aid of government officials, and against the opposition of some tribal members.",
    poster_path: null,
    media_type: "movie",
    genre_ids: [99],
    popularity: 1.159,
    release_date: "1949-08-15",
    video: false,
    vote_average: 4.833,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 71915,
    title: "AC/DC - Documentation",
    original_language: "de",
    original_title: "AC/DC - Dokumentation",
    overview:
      "A detailed documentary about the band AC/DC. It begins with the beginnings of the band, which was still young at the time, through Bon Scott's death to their great successes. An exciting story for every fan who also wants to see behind the scenes of AC/DC.",
    poster_path: null,
    media_type: "movie",
    genre_ids: [],
    popularity: 1.4,
    release_date: "2013-01-20",
    video: false,
    vote_average: 5,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    id: 872585,
    title: "Oppenheimer",
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.",
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    media_type: "movie",
    genre_ids: [18, 36],
    popularity: 885.519,
    release_date: "2023-07-19",
    video: false,
    vote_average: 8.315,
    vote_count: 1392,
  },
  {
    adult: false,
    backdrop_path: "/znUYFf0Sez5lUmxPr3Cby7TVJ6c.jpg",
    id: 447277,
    title: "The Little Mermaid",
    original_language: "en",
    original_title: "The Little Mermaid",
    overview:
      "The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.",
    poster_path: "/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
    media_type: "movie",
    genre_ids: [12, 10751, 14, 10749],
    popularity: 2035.029,
    release_date: "2023-05-18",
    video: false,
    vote_average: 6.481,
    vote_count: 1393,
  },
  {
    adult: false,
    backdrop_path: "/14GEZCzCGhV7FMFaWi4Ec22Kcai.jpg",
    id: 459003,
    title: "Mavka: The Forest Song",
    original_language: "uk",
    original_title: "Мавка: Лісова пісня",
    overview:
      "Mavka — a Soul of the Forest and its Warden — faces an impossible choice between love and her duty as guardian to the Heart of the Forest, when she falls in love with a human — the talented young musician Lukas.",
    poster_path: "/eeJjd9JU2Mdj9d7nWRFLWlrcExi.jpg",
    media_type: "movie",
    genre_ids: [16, 12, 10751, 14],
    popularity: 1160.198,
    release_date: "2023-03-02",
    video: false,
    vote_average: 7.407,
    vote_count: 236,
  },
  {
    adult: false,
    backdrop_path: "/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
    id: 447365,
    title: "Guardians of the Galaxy Vol. 3",
    original_language: "en",
    original_title: "Guardians of the Galaxy Vol. 3",
    overview:
      "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    media_type: "movie",
    genre_ids: [878, 12, 28],
    popularity: 1592.277,
    release_date: "2023-05-03",
    video: false,
    vote_average: 8.085,
    vote_count: 3870,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    id: 385687,
    title: "Fast X",
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    media_type: "movie",
    genre_ids: [28, 80, 53],
    popularity: 1449.925,
    release_date: "2023-05-17",
    video: false,
    vote_average: 7.324,
    vote_count: 3113,
  },
];
